sudo: false
language: python
install: pip install tox
matrix:
  include:
    - python: "2.6"
      env: TOX_ENV=py26
    - python: "2.7"
      env: TOX_ENV=py27
    - python: "3.6"
      env: TOX_ENV=py36
    - python: "2.7"
      env: TOX_ENV=static
    # alt-src not available on PyPI
    #- python: "2.7"
    #  env: TOX_ENV=pidiff
    # alt-src docs not implemented
    #- python: "2.7"
    #  env: TOX_ENV=docs
script: tox -e $TOX_ENV
