sudo: false
language: python
install: pip install tox
matrix:
  include:
    - python: "2.6"
      env: TOX_ENV=py26
      dist: trusty
    - python: "2.7"
      env: TOX_ENV=cov-travis
    - python: "3.6"
      env: TOX_ENV=py36
script: tox -e $TOX_ENV
